
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace trial.Models
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
public partial class Seat
{
        [DataMember]
    public int Seat_no { get; set; }
        [DataMember]
    public int Bus_ID { get; set; }
        [DataMember]
    public string seat_status { get; set; }
        [DataMember]
    public string passenger_name { get; set; }
        [DataMember]
    public Nullable<int> booking_id { get; set; }



    public virtual Booking Booking { get; set; }

    public virtual Bus_Details Bus_Details { get; set; }

}

}
